#!/bin/bash

PROGNAME=$(basename $0)
INSTALLER_DIR="/opt/amqpinflux/"
PREFIX="/usr"

ln -sf $INSTALLER_DIR/embedded $INSTALLER_DIR/env || error_exit "Cannot link $INSTALLER_DIR/env"

echo "Thank you for installing cloudify-amqp-influxdb!"