driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/cloudify']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: centos-7.1
    run_list: yum-epel::default
  - name: centos-6.6
    run_list: yum-epel::default
  - name: centos-5.11
    run_list: yum-epel::default
  - name: debian-7.8
    run_list: apt::default
  - name: debian-6.0.10
    run_list: apt::default
  - name: freebsd-10.1
    run_list: freebsd::portsnap
  - name: freebsd-9.3
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: windows-2012r2-build
    driver:
      name: ec2
    driver_config:
      image_id: ami-9a0558f0
      region: us-east-1
      availability_zone: b
      security_group_ids: ['sg-CHANGEME']
      subnet_id: subnet-CHANGEME
      instance_type: t2.micro
      user_data: "user-data/windows-ec2-build.ps1"
      require_chef_omnibus: true
      tags: {
        "Name": "cloudify-cli msi build"
      }
      aws_ssh_key_id: key-CHANGEME
      associate_public_ip: true
    transport:
      username: vagrant
      password: vagrant
  - name: windows-2012r2
    driver:
      name: ec2
    driver_config:
      image_id: ami-9a0558f0
      region: us-east-1
      availability_zone: b
      security_group_ids: ['sg-CHANGEME']
      subnet_id: subnet-CHANGEME
      instance_type: t2.micro
      user_data: "user-data/windows-ec2-test.ps1"
      tags: {
        "Name": "cloudify-cli msi test"
      }
      aws_ssh_key_id: key-CHANGEME
      associate_public_ip: true
    transport:
      username: vagrant
      password: vagrant

suites:
  - name: default
    run_list: 
      - omnibus::default
      - cloudify_cli::default 
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/cloudify
        build_dir:           /home/vagrant/cloudify
        build_project:       cloudify
    includes: [
      'centos-6.6',
      'ubuntu-12.04'
    ]
  - name: ms
    run_list:
      - omnibus::default
      - cloudify_cli::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_password: vagrant
        install_dir:         c:\cloudify
        build_dir:           c:\vagrant
        build_project:       cloudify-windows
    includes: [
      'windows-2012r2-build'
    ]
  - name: cloudify
    run_list: 
      - cloudify_cli::install 
    includes: [
      'centos-6.6',
      'centos-7.1',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'windows-2012r2'
    ]
